name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.16.1
  - ipywidgets=7.5.1
  - nodejs=10.13.0
  - notebook=6.0.3
  - numpy=1.19.1
  - numpy-base=1.19.1
  - python=3.8.5
  - widgetsnbextension=3.5.1
  - conda=4.8.3
  - conda-build=3.18.11
  - conda-env=2.6.0
  - conda-package-handling=1.6.1
  - conda-verify=3.4.2
  - pip=20.1.1
  - pip:
    - bqplot==0.11.0
    - matplotlib==3.3.0
    - nbdime==2.0.0
    - nbformat==4.4.0
    - nbinteract==0.2.5
    - matplotlib==3.3.0

